const mongoose = require('mongoose');//Para conectarse a la DB
const Animals = require('../api/models/animal.model');//Para crear objeto de DB
const dotenv = require('dotenv');//Para conectarse DB
dotenv.config();
//---------------------------------INPUT---------------------------------

const animals = [
{
    "especie":"Ave",
    "edad":"Jóven",
    "fechaDeNacimiento": "2020-01-23",
    "sexo": "Hembra",
    "tamaño": "Pequeño",
    "peso": 0.3,
    "vacunado": false,
    "desparasitado": false,
    "sano": true,
    "esterilizado": false,
    "identificado": true,
    "microchip": false,
    "nombre": "Kiwi",
    "image":"https://www.elmueble.com/medio/2022/10/18/periquito_f1c7f29e_900x900.jpg",
    "imagenes":[
        "https://www.elmueble.com/medio/2022/10/18/periquito_f1c7f29e_900x900.jpg",
        "https://i.blogs.es/f5f0e5/parakeet-2352743_960_720/840_560.jpg",
        "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a4f77143-2a8a-4279-a1ce-251761516659/d8ab89c-e5acf2de-3c23-4ecf-aa7b-b586e5de300a.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2E0Zjc3MTQzLTJhOGEtNDI3OS1hMWNlLTI1MTc2MTUxNjY1OVwvZDhhYjg5Yy1lNWFjZjJkZS0zYzIzLTRlY2YtYWE3Yi1iNTg2ZTVkZTMwMGEuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.eHcBe7xVGz1EBQ5mV83Imd89HaEVKCseLUZikYZxrq8"
    ],
    "ubicacion": "Comunidad de Madrid",
    "ciudad": "Madrid",
    "personalidad": ["Bueno con niños","Timido","Cauteloso","Juguetón","A veces ladro, maullo..."],
    "historia":" Soy un pollito que se callo del nido porque me empujo el cuco, el res….",
    "aSaber": "Me da miedo la oscuridad y necesito mimos por las noches",
    "requisitosAdopcion":"Tener mosquiteras en las ventanas, porque me da por volar",
    "tasaAdopcion": 130,
    "seEnvia": "Se realiza el envio a toda la peninsula, va solo volando",
    "adoptionState": "En proceso"
},
{
    "especie": "Ave",
    "edad":"Jóven",
    "fechaDeNacimiento": "2020-03-07",
    "sexo": "Macho",
    "tamaño": "Pequeño",
    "peso": 0.3,
    "vacunado": true,
    "desparasitado": true,
    "sano": true,
    "esterilizado": false,
    "identificado": true,
    "microchip": false,
    "nombre": "Blue",
    "image":"https://static.wikia.nocookie.net/birdland/images/6/62/Perico_azul_real.png/revision/latest?cb=20110722202640&path-prefix=es",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-IJk-wXq-G0R6MWO09lKIGRx8fmib64fDUA&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-IJk-wXq-G0R6MWO09lKIGRx8fmib64fDUA&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAgJALgPNGXHzZ37HjdhQTH4TU4N8DW49umg&usqp=CAU"
    ],
    "ubicacion": "Comunidad de Madrid",
    "ciudad": "Madrid",
    "personalidad": ["Cantor."],
    "historia":"El hermano menos querido de Kiwi.",
    "aSaber": "Es kiwi version azul,pero menos querido.",
    "requisitosAdopcion":"Canatarle Todos los dias.",
    "tasaAdopcion": 15,
    "seEnvia": "Si pero este no llega volando",
    "adoptionState": "En proceso"
},
{
    "especie": "Perro",
    "fechaDeNacimiento": "2017-08-27",
    "edad":"Jóven",
    "sexo": "Macho",
    "tamaño": "Grande",
    "peso": 15,
    "vacunado": true,
    "desparasitado": true,
    "sano": true,
    "esterilizado": true,
    "identificado": true,
    "microchip": true,
    "nombre": "Max",
    "image":"https://animalesenpantalla.files.wordpress.com/2010/05/milo.jpg",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRUS2-8HRNZ6wu4_vrADvoVDlzk2Ai0hd_Eg&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq6m9jKDGu6gNWhEFD--PMI9C0OpRnmnZMyg&usqp=CAU",
        "https://st1.uhttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuaHd_brXiS_g2v-PqIXKZZk2osmKtQOrFYQ&usqp=CAU"
    ],
    "ubicacion":"USA" ,
    "ciudad": "Miami",
    "personalidad": ["Comico","famoso"],
    "historia":"Fue el perro de  Jim Carrey y logro tener poderes.",
    "aSaber": "Puede ser peligroso y tierno al mismo tiempo.",
    "requisitosAdopcion":"No dejar mascaras a su alcance.",
    "tasaAdopcion": 201,
    "seEnvia": "Si A quien pueda con el",
    "adoptionState": "En proceso"
   },
{
    "especie": "Gato",
    "edad":"Jóven",
    "fechaDeNacimiento": "1994-10-11",
    "sexo": "Hembra",
    "tamaño": "Mediano",
    "peso": 5,
    "vacunado": true,
    "desparasitado": true,
    "sano": true,
    "esterilizado": true,
    "identificado": true,
    "microchip": true,
    "nombre": "Simba",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNDo7fx48i7JYVodoZo0IqpAmexPkB5KRgBA&usqp=CAU",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9iGbnwnO-Ujhl6BIN5j4PDLtcJ3mIdJLSGA&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHlb1-lWggwIAkmj4k6gtY_QS6fl9GjmrLVA&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGyx1iEM5kI2m4yIO0R6lwrF1GclCZ9BvP-g&usqp=CAU"
    ],
    "ubicacion":"Africa" ,
    "ciudad": "_Africa",
    "personalidad": ["Lider","amigable","flojo"],
    "historia":"Gracias a su  tio vivio muchas aventuras fantasticas",
    "aSaber": "Nala era su media hermana",
    "requisitosAdopcion":"Hakuna Matata",
    "tasaAdopcion": 145,
    "seEnvia": "No",
    "adoptionState": "En proceso"

},
{
    "especie": "Gato" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "2012-06-10" ,
    "sexo": "Hembra" ,
    "tamaño": "Mediano",
    "peso": 4.5,
    "vacunado": true,
    "desparasitado": true ,
    "sano":true ,
    "esterilizado": true,
    "identificado": true,
    "microchip":false,
    "nombre": "Saphira" ,
    "image": "https://t2.ea.ltmcdn.com/es/razas/9/7/1/siames_179_0_orig.jpg",
    "imagenes":[
        "https://t2.ea.ltmcdn.com/es/razas/9/7/1/siames_179_0_orig.jpg",
        "https://static.miscota.com/consejos/wp-content/uploads/2016/11/shutterstock_87157474.jpg",
        "https://img.remediosdigitales.com/94c1d4/gato-siames-1/1366_2000.jpeg"
    ],
    "ubicacion":"Madrid" ,
    "ciudad": "Madrid",
    "personalidad": ["Juguetona"],
    "historia":"Me encontraron en Galicia, aunque en realidad, yo los encontré a ellos...",
    "aSaber": "Es una gata muy juguetona que necesita atencion, correr y mimos por las noches, si no, te pisara la cabeza para despertarte.",
    "requisitosAdopcion":"Ser una persona activa y que no le importe recibir atencion",
    "tasaAdopcion": 10,
    "seEnvia": "A Madrid solo",
    "adoptionState": "En proceso"

},{
    "especie": "Gato" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "2012-06-10" ,
    "sexo": "Hembra" ,
    "tamaño": "Mediano",
    "peso": 4.5,
    "vacunado": true,
    "desparasitado": true ,
    "sano":true ,
    "esterilizado": true,
    "identificado": true,
    "microchip":false,
    "nombre": "Saphira" ,
    "image":"https://t2.ea.ltmcdn.com/es/razas/9/7/1/siames_179_0_orig.jpg",
    "imagenes":[
        "https://t2.ea.ltmcdn.com/es/razas/9/7/1/siames_179_0_orig.jpg",
        "https://static.miscota.com/consejos/wp-content/uploads/2016/11/shutterstock_87157474.jpg",
        "https://img.remediosdigitales.com/94c1d4/gato-siames-1/1366_2000.jpeg"
    ],
    "ubicacion":"Madrid" ,
    "ciudad": "Madrid",
    "personalidad":[ "Juguetona"],
    "historia":"Me encontraron en Galicia, aunque en realidad, yo los encontré a ellos...",
    "aSaber": "Es una gata muy juguetona que necesita atencion, correr y mimos por las noches, si no, te pisara la cabeza para despertarte.",
    "requisitosAdopcion":"Ser una persona activa y que no le importe recibir atencion",
    "tasaAdopcion": 10,
    "seEnvia": "A Madrid solo",
    "adoptionState": "En proceso"
},{
    "especie": "Perro" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "2015-12-09" ,
    "sexo": "Hembra" ,
    "tamaño": "Mediano",
    "peso": 12.5,
    "vacunado": true,
    "desparasitado": true ,
    "sano":true ,
    "esterilizado": true,
    "identificado": true,
    "microchip":true,
    "nombre": "mondongo" ,
    "image":"https://images.hindustantimes.com/img/2021/11/03/1600x900/Doge_meme_dog_birthday_1635925455510_1635925462309.PNG",
    "imagenes":[
        "https://cloudfront-us-east-1.images.arcpublishing.com/radiomitre/H6Y67TBFUNHZTFFBEB4YIUTL7U.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUB5YANeh46I_a66viKira65D9AqtLad6aZQ&usqp=CAU",
        "https://cdn.decrypt.co/wp-content/uploads/2023/02/Shiba-Inu-Couch-shutterstock_1481685371-16x9-1-gID_4.jpg"
    ],
    "ubicacion":"Valencia" ,
    "ciudad": "Valencia",
    "personalidad": ["Odiosa"],
    "historia":"Un dia estaba sentada de lo mas tranquila y  de repente mi dueña me toman una fota y la sube a internet. Ahora soy un icono del internet.",
    "aSaber": "El una raza de perro muy guapa y de la cual podras sacar muchos memes",
    "requisitosAdopcion":"Si le haces algo te reviento,payaso",
    "tasaAdopcion": 15,
    "seEnvia": "A Valecnia y su comunidad",
    "adoptionState": "En proceso"
},{
    "especie": "Conejo" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "1938-07-27" ,
    "sexo": "Macho" ,
    "tamaño": "Grande",
    "peso": 9.5,
    "vacunado": true,
    "desparasitado": true ,
    "sano":true ,
    "esterilizado": false,
    "identificado": true,
    "microchip":false,
    "nombre": "bugs bunny" ,
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbqj4vZgf_2WMIvejd4UfQAuAnFUQNiFItMg&usqp=CAU",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAUcPYonHHkcrbU8IRAOlmNIlVJuP1PLf8CQ&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUB5YANeh46I_a66viKira65D9AqtLad6aZQ&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1fzE_BLttBx3MPd48SUx0wxZwTkELdPK9-A&usqp=CAU"
    ],
    "ubicacion":"USA" ,
    "ciudad": "Texas",
    "personalidad": ["Cabron."],
    "historia":"un alocado conejo en las series de los Looney Tunes y Merrie Melodies producidas por Leon Schlesinger para la compañía Warner Bros.",
    "aSaber": "Es un Cabron.",
    "requisitosAdopcion":"¿Que hay de nuevo viejo?.",
    "tasaAdopcion": 0,
    "seEnvia": "Todo el mundo",
    "adoptionState": "En proceso"
},{
    "especie": "Reptil" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "1988-07-27" ,
    "sexo": "Macho" ,
    "tamaño": "Grande",
    "peso": 80,
    "vacunado": true,
    "desparasitado": true ,
    "sano":true ,
    "esterilizado": false,
    "identificado": true,
    "microchip":true,
    "nombre": "Diego" ,
    "image":"https://ichef.bbci.co.uk/news/640/cpsprodpb/515C/production/_91182802_hi035254269.jpg",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJfrTTqvuRqDeox-2V6fwHAuAPLRTCbMR4HA&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzFiw_JXE5UvS0n8UXZ6jihQ34QAOCvEVVEA&usqp=CAU",
        "https://st1.uvnimg.com/c2/f7/b09ce82d4c5f8496ef46b5eb76ad/1e902725420773b35bda0338e5f48704b339763d.jpg"
    ],
    "ubicacion":"Galápagos." ,
    "ciudad": "Isla de Galápagos.",
    "personalidad": ["Fucker."],
    "historia":"Diego es el padre de 800 tortugas de una rara especie gigante de Galápagos.Con más de 100 años y es famosa debido a su gran ayuda para la supervivencia de su especie en las islas Galápagos.",
    "aSaber": "Es una tortuga muy vieja.",
    "requisitosAdopcion":"Tener una reserva animal.",
    "tasaAdopcion": 0,
    "seEnvia": "No",
    "adoptionState": "En proceso"
},{
    "especie": "Hurón" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "2020-07-27" ,
    "sexo": "Macho" ,
    "tamaño": "Pequeño",
    "peso": 0.8,
    "vacunado": true,
    "desparasitado": true ,
    "sano":true ,
    "esterilizado": true,
    "identificado": true,
    "microchip":true,
    "nombre": "Manchitas" ,
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6ZaK-As6E3VmO6fJZVdRM22Gqvq69AjgH7w&usqp=CAU",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh6hX6Okhw03dIkCV9nFBi84iu--bx6Z3ycA&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZuymZ3DaQcgFZ9pIk13FdXhUKdSc0mBBupQ&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrivsGjEqtjnnWQCzK2nZEAgjlvKFk9WPvgA&usqp=CAU"
    ],
    "ubicacion":"Madrid" ,
    "ciudad": "Madrid",
    "personalidad": ["Jugueton","travieso","mordelon"],
    "historia":"Fue encontrado en caja en la plaza de Atocha.",
    "aSaber": "Esconde las cosas, asi que se mas ordenad@",
    "requisitosAdopcion":"Poder dedicarle mucho tiempo",
    "tasaAdopcion": 15,
    "seEnvia": "No",
    "adoptionState": "En proceso"
}
,{
    "especie": "Arácnido o insecto" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "2020-08-01" ,
    "sexo": "Hembra" ,
    "tamaño": "Mediano",
    "peso": 0.2,
    "vacunado": false,
    "desparasitado": false ,
    "sano":true ,
    "esterilizado": true,
    "identificado": true,
    "microchip":false,
    "nombre": "Spidi" ,
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ421gVpWLqoWe_WU00Pd7Cz8qqoqJiOGXiew&usqp=CAU",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR__k8AmbLaXsumokXIaxM974D7cb7nC95hCw&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZuymZ3DaQcgFZ9pIk13FdXhUKdSc0mBBupQ&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCwqa5_8VWmKcCA0jA3K0D6aXECERSCqYkRA&usqp=CAU"
    ],
    "ubicacion":"Bilbao" ,
    "ciudad": "Bilbao",
    "personalidad": ["Jugueton","travieso","mordelona"],
    "historia":"La compraron pensado que daria poderes con su mordedura.Resulto que no",
    "aSaber": "NO, da poderes",
    "requisitosAdopcion":"Darle muchos mimos",
    "tasaAdopcion": 15,
    "seEnvia": "si,cuidado al abrir la caja",
    "adoptionState": "En proceso"
},{
    "especie": "Pez" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "20223-01-11" ,
    "sexo": "Macho" ,
    "tamaño": "Mediano",
    "peso": 0.8,
    "vacunado": false,
    "desparasitado": false ,
    "sano":true ,
    "esterilizado": false,
    "identificado": false,
    "microchip":false,
    "nombre": "Pargo",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq3mn79q-FK6egKe-F9OxQQLZCAE41ej-Bvg&usqp=CAU",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSed1gPH2x2AbQ8nQ4_ndbZIUhsJMcpC4yUw&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgvowrgSdc5rWC7VEiNtT1hUKNlVTfC4UATQ&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKn_fpzCAmg2PsL-nwj1duV6mfiNPIyhGJlw&usqp=CAU"
    ],
    "ubicacion":"Falcon" ,
    "ciudad": "Falcon",
    "personalidad": ["Sabroso","Pescado Frito","Tostones"],
    "historia":"Pescado frito con tostonesy ensalada rayada",
    "aSaber": "Esto no era una pagina de recetas",
    "requisitosAdopcion":"Acompañarlo con un papelon con limon ",
    "tasaAdopcion": 25,
    "seEnvia": "si",
    "adoptionState": "En proceso"
}
,{
    "especie": "Cobaya" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "20222-10-11" ,
    "sexo": "Hembra" ,
    "tamaño": "Pequeño",
    "peso": 0.6,
    "vacunado": true,
    "desparasitado": true ,
    "sano":true ,
    "esterilizado": true,
    "identificado": true,
    "microchip":false,
    "nombre": "Spidi",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp4YtfyM2CAsDWMmEky_zBelF7vy9bDYeHmw&usqp=CAU",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXoshT1yGCcaAEC_bCIoN5rbNP-dYF3cv3lw&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgN6MnJ2QUDR5ECjFk24abhqmKj5RQqX-bLQ&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ65CqKDSp7Xox6edZlJBf8JqXbI6Rdw9lVgQ&usqp=CAU"
    ],
    "ubicacion":"San Sebastian" ,
    "ciudad": "San Sebastian",
    "personalidad": ["Desorintado","Gloton","Ruidoso"],
    "historia":"La encontaron en una fruteria comiendo se to",
    "aSaber": "Cuidado con su ternura",
    "requisitosAdopcion":"Darle muchos pasto ",
    "tasaAdopcion": 18,
    "seEnvia": "si",
    "adoptionState": "En proceso"
},{
    "especie": "Anfibio" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "20220-10-11" ,
    "sexo": "Macho" ,
    "tamaño": "Pequeño",
    "peso": 0.3,
    "vacunado": false,
    "desparasitado": false ,
    "sano":true ,
    "esterilizado": false,
    "identificado": false,
    "microchip":false,
    "nombre": "Saltitos",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSE3MMSahbUclV3t3wyLBpncxhnpt7sE7PeMw&usqp=CAU",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBUz4sLrf_ll20tuGfnLGLasv9iNcJ4Or7yA&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8uzzPPvw4jmJi7qr5RBtlDccEz28lEa0LWg&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb-6GXBwnNH89B2HWZAXyeEjZi2M0fpKbulw&usqp=CAU"
    ],
    "ubicacion":"Amazonas" ,
    "ciudad": "Amazonas",
    "personalidad": ["Venenosa","Tranquila","Cautelosa"],
    "historia":"Son ranas guapas de color pero tambien es indicativo de que son venenosas",
    "aSaber": "Cuidado no tocarlas sin guantes",
    "requisitosAdopcion":"Mantenerlas hidratadas ",
    "tasaAdopcion": 98,
    "seEnvia": "si",
    "adoptionState": "En proceso"
},{
    "especie": "Reptil" ,
    "edad":"Jóven",
    "fechaDeNacimiento": "20218-11-11" ,
    "sexo": "Macho" ,
    "tamaño": "Grande",
    "peso": 85,
    "vacunado": true,
    "desparasitado": true ,
    "sano":true ,
    "esterilizado": true,
    "identificado": true,
    "microchip":true,
    "nombre": "Abracitos",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfTGqXd6JSETyf4v9ZfA3JFNGNnOkFh5TaYQ&usqp=CAU",
    "imagenes":[
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGoRwwpn8rPscMKjGietVs3X1XpS-CSneV5Q&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_SZhMh9DFuhskhPGR73S4PrxYc5I3S47A6A&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7ZTA8Al0NkAcVI5KVouX2_ebLlRYw6ZPORQ&usqp=CAU"
    ],
    "ubicacion":"Amazonas" ,
    "ciudad": "Amazonas",
    "personalidad": ["Tranquila","Le gusta abrazar","Glotona"],
    "historia":"La guarida de la anaconda cabezona",
    "aSaber": "Pica pero no muerde",
    "requisitosAdopcion":"Dejar darse amor por ella ",
    "tasaAdopcion": 100,
    "seEnvia": "si",
    "adoptionState": "En proceso"
}                    
];

mongoose.set("strictQuery", false);

//Connecto to DB
mongoose.connect(process.env.DB_URL ,{
    useNewUrlParser: true,
    useUnifiedTopology: true,
}).then(async () => {
    const allAnimals = await Animals.find();
    if(allAnimals.length > 0) {
        await Animals.collection.drop();
        console.log(`All animals were deleted from <${Animals.db.name}.${Animals.collection.name}>`);
    }
}).catch((error) => console.log("Error occurred while deleting animals: ", error))
.then(async () => {
    const animalsMap = animals.map((item) => new Animals(item));
    await Animals.insertMany(animalsMap);
    console.log(`All animals were created in <${Animals.db.name}.${Animals.collection.name}>`);
})
.catch((error) => console.log("Error occurred while creating animals: ", error))
.finally(() => mongoose.disconnect());