const mongoose = require('mongoose');//Para conectarse a la DB
const Animals = require('../api/models/chef.model');//Para crear objeto de DB
const dotenv = require('dotenv');//Para conectarse DB
dotenv.config();
//---------------------------------INPUT---------------------------------

const animals = [
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
},
{
    "_id": "63c17fe00fc41a6e4adbe580",
    "especie": "Xi Xao",
    "fecha de nacimiento": "Kenia",
    "sexo": 3,
    "tamaño": "Kenia",
    "peso": "Kenia",
    "vacunado": "Kenia",
    "desparasitado": "Kenia",
    "sano": "Kenia",
    "esterilizado": "Kenia",
    "identificado": "Kenia",
    "microchip": "Kenia",
    "nombre": "Kenia",
    "ubicacion": "Kenia",
    "ciudad": "Kenia",
}
];

mongoose.set("strictQuery", false);

//Connecto to DB
mongoose.connect(process.env.DB_URL ,{
    useNewUrlParser: true,
    useUnifiedTopology: true,
}).then(async () => {
    const allAnimals = await Chef.find();
    if(allAnimals.length > 0) {
        await Animals.collection.drop();
        console.log(`All animals were deleted from <${Animals.db.name}.${Animals.collection.name}>`);
    }
}).catch((error) => console.log("Error occurred while deleting animals: ", error))
.then(async () => {
    const animalsMap = animals.map((item) => new Animals(item));
    await Animals.insertMany(animalsMap);
    console.log(`All animals were created in <${Animals.db.name}.${Animals.collection.name}>`);
})
.catch((error) => console.log("Error occurred while creating animals: ", error))
.finally(() => mongoose.disconnect());